# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# in main branch
name: Check output

on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pypsa
        python -m pip install pandas
        python -m pip install openpyxl
        python -m pip install gurobipy
        
    - shell: bash
      id: write-license
      env:
        LICENSE: ${{ secrets.GUROBI_LIC   }}
      run: |
        mkdir /opt/gurobi
        echo "$LICENSE" > /opt/gurobi/gurobi.lic
        # echo "grb_license_file=$PWD/gurobi.lic" >> $GITHUB_OUTPUT
        
    - name: run_pypsa test
      run:
        python run_pypsa.py -f test/test_case.xlsx
        
    - name: Save xlsx artifact
      uses: actions/upload-artifact@v4
      with:
        name: output_xlsx
        path: output_data/test_case/test_prefix.xlsx
        
    - name: compare output
      run:
        python test/test_compare_output.py

    # Uncomment this section to upload output file(s) at the end of this job
    #- uses: actions/upload-artifact@v4
    #  with:
    #    name: my-artifact
    #    path: test_output.txt
